# Generated by Django 4.2.7 on 2023-11-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/Users/roflanpotsan/workspace/copycat/img/pfp-default.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('rating', models.BigIntegerField(null=True)),
                ('date_submitted', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copycat_app.profile')),
            ],
        ),
    ]
