# Generated by Django 4.2.7 on 2023-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0002_questionrating_answerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/pfp-default.png', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
