# Generated by Django 4.2.7 on 2023-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0003_tag_answer_question_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uses',
            field=models.BigIntegerField(default=0),
        ),
    ]
