# Generated by Django 4.2.7 on 2023-12-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copycat_app', '0003_alter_answer_rating_alter_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrating',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_ratings', to='copycat_app.question'),
        ),
        migrations.AlterField(
            model_name='answerrating',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to='copycat_app.question'),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
