# Generated by Django 4.2.7 on 2023-12-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0004_alter_answerrating_answer_alter_answerrating_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerrating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answerrating',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_ratings', to='copycat_app.profile'),
        ),
        migrations.AddField(
            model_name='questionrating',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to='copycat_app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='answerrating',
            unique_together={('profile', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionrating',
            unique_together={('profile', 'question')},
        ),
        migrations.RemoveField(
            model_name='answerrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionrating',
            name='user',
        ),
    ]
