# Generated by Django 4.2.7 on 2023-12-06 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0006_alter_answer_date_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 43, 2, 150437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 43, 2, 149898, tzinfo=datetime.timezone.utc)),
        ),
    ]
