# Generated by Django 4.2.7 on 2023-12-06 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0007_alter_answer_date_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 44, 32, 52390, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='answerrating',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_ratings', to='copycat_app.answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 44, 32, 51799, tzinfo=datetime.timezone.utc)),
        ),
    ]
