# Generated by Django 4.2.7 on 2023-12-21 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat_app', '0008_alter_answer_date_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 14, 59, 30, 735543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 14, 59, 30, 734811, tzinfo=datetime.timezone.utc)),
        ),
    ]
